"""
report_generator.py

Creates a professional PDF Field Assessment Report from a FieldReport.
"""

from __future__ import annotations

import io
from datetime import datetime

from PIL import Image as PILImage

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


# ============================================================
# HELPERS
# ============================================================

STATUS_LABELS = {
    "healthy": "Healthy",
    "moderate": "Moderate",
    "needs_attention": "Needs Attention",
    "bare": "Bare",
}


def _image_from_buffer(
    buffer: io.BytesIO,
    max_width: float,
    max_height: float,
):
    """Create a ReportLab image while preserving aspect ratio."""

    buffer.seek(0)

    image = PILImage.open(buffer)

    width, height = image.size

    scale = min(
        max_width / width,
        max_height / height,
    )

    return Image(
        buffer,
        width=width * scale,
        height=height * scale,
    )


def _status_color(status: str):
    """Return the report color associated with a zone status."""

    return {
        "healthy": colors.HexColor("#2e7d32"),
        "moderate": colors.HexColor("#f9a825"),
        "needs_attention": colors.HexColor("#ef6c00"),
        "bare": colors.HexColor("#c62828"),
    }.get(status, colors.grey)


def _header_footer(canvas, doc):
    """Draw a simple professional header/footer."""

    canvas.saveState()

    width, height = A4

    # --------------------------------------------------------
    # HEADER
    # --------------------------------------------------------

    canvas.setStrokeColor(
        colors.HexColor("#2e7d32")
    )

    canvas.setLineWidth(1.2)

    canvas.line(
        18 * mm,
        height - 16 * mm,
        width - 18 * mm,
        height - 16 * mm,
    )

    canvas.setFont(
        "Helvetica-Bold",
        8,
    )

    canvas.setFillColor(
        colors.HexColor("#2e7d32")
    )

    canvas.drawString(
        18 * mm,
        height - 12 * mm,
        "FIELDSCANNER",
    )

    canvas.setFont(
        "Helvetica",
        8,
    )

    canvas.setFillColor(
        colors.grey
    )

    canvas.drawRightString(
        width - 18 * mm,
        height - 12 * mm,
        "Agricultural Field Assessment",
    )

    # --------------------------------------------------------
    # FOOTER
    # --------------------------------------------------------

    canvas.setStrokeColor(
        colors.HexColor("#dddddd")
    )

    canvas.setLineWidth(0.5)

    canvas.line(
        18 * mm,
        14 * mm,
        width - 18 * mm,
        14 * mm,
    )

    canvas.setFont(
        "Helvetica",
        7,
    )

    canvas.setFillColor(
        colors.grey
    )

    canvas.drawString(
        18 * mm,
        9 * mm,
        "Generated by FieldScanner",
    )

    canvas.drawRightString(
        width - 18 * mm,
        9 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()


# ============================================================
# PDF GENERATION
# ============================================================

def generate_pdf_report(
    report,
    original_image,
    overlay_buffer=None,
    heatmap_buffer=None,
    confidence_buffer=None,
    target_coverage_pct=80.0,
    field_name="field",
):
    """
    Generate a professional PDF report.

    Parameters
    ----------
    report:
        FieldReport returned by FieldAnalyzer.

    original_image:
        RGB NumPy image array.

    overlay_buffer:
        BytesIO containing the vegetation overlay.

    heatmap_buffer:
        BytesIO containing the zone heatmap.

    confidence_buffer:
        Optional BytesIO containing a vegetation-confidence map.

    target_coverage_pct:
        Target vegetation coverage.

    field_name:
        Name displayed in the report.

    Returns
    -------
    BytesIO
        PDF file in memory.
    """

    pdf_buffer = io.BytesIO()

    document = SimpleDocTemplate(
        pdf_buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=22 * mm,
        bottomMargin=20 * mm,
        title="FieldScanner Field Assessment Report",
        author="FieldScanner",
    )

    styles = getSampleStyleSheet()

    # ========================================================
    # STYLES
    # ========================================================

    title_style = ParagraphStyle(
        "FieldTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=25,
        leading=30,
        textColor=colors.HexColor("#1b5e20"),
        alignment=TA_CENTER,
        spaceAfter=5 * mm,
    )

    subtitle_style = ParagraphStyle(
        "FieldSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#666666"),
        alignment=TA_CENTER,
        spaceAfter=10 * mm,
    )

    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        textColor=colors.HexColor("#1b5e20"),
        spaceBefore=6 * mm,
        spaceAfter=4 * mm,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor("#333333"),
        spaceAfter=3 * mm,
    )

    small_style = ParagraphStyle(
        "Small",
        parent=body_style,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#666666"),
    )

    story = []

    # ========================================================
    # COVER / SUMMARY
    # ========================================================

    story.append(
        Spacer(
            1,
            8 * mm,
        )
    )

    story.append(
        Paragraph(
            "FieldScanner",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "Agricultural Field Assessment Report",
            subtitle_style,
        )
    )

    story.append(
        Paragraph(
            f"<b>{field_name}</b>",
            ParagraphStyle(
                "FieldName",
                parent=subtitle_style,
                fontSize=14,
                textColor=colors.HexColor("#333333"),
            ),
        )
    )

    story.append(
        Paragraph(
            f"Analysis generated on "
            f"{datetime.now().strftime('%d %B %Y, %H:%M')}",
            subtitle_style,
        )
    )

    # ========================================================
    # KEY METRICS
    # ========================================================

    story.append(
        Paragraph(
            "Executive Summary",
            section_style,
        )
    )

    coverage = report.overall_green_pct

    coverage_status = (
        "Target achieved"
        if coverage >= target_coverage_pct
        else "Below target"
    )

    needing = (
        report.status_breakdown["needs_attention"]
        + report.status_breakdown["bare"]
    )

    total_cells = (
        report.grid_rows
        * report.grid_cols
    )

    coverage_gap = max(
        0.0,
        target_coverage_pct - coverage,
    )

    metric_data = [
        [
            Paragraph(
                "<b>Visible Vegetation</b>",
                body_style,
            ),
            Paragraph(
                "<b>Target Coverage</b>",
                body_style,
            ),
            Paragraph(
                "<b>Coverage Gap</b>",
                body_style,
            ),
            Paragraph(
                "<b>Attention Zones</b>",
                body_style,
            ),
        ],
        [
            Paragraph(
                f"{coverage:.1f}%",
                body_style,
            ),
            Paragraph(
                f"{target_coverage_pct:.1f}%",
                body_style,
            ),
            Paragraph(
                f"{coverage_gap:.1f}%",
                body_style,
            ),
            Paragraph(
                f"{needing} / {total_cells}",
                body_style,
            ),
        ],
    ]

    metric_table = Table(
        metric_data,
        colWidths=[
            42 * mm,
            42 * mm,
            42 * mm,
            42 * mm,
        ],
    )

    metric_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#e8f5e9"),
                ),
                (
                    "BACKGROUND",
                    (0, 1),
                    (-1, 1),
                    colors.HexColor("#f8faf8"),
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.8,
                    colors.HexColor("#c8e6c9"),
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    colors.HexColor("#dddddd"),
                ),
                (
                    "ALIGN",
                    (0, 0),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    story.append(metric_table)

    story.append(
        Spacer(
            1,
            6 * mm,
        )
    )

    # ========================================================
    # AREA INFORMATION
    # ========================================================

    if report.total_area_m2 is not None:

        story.append(
            Paragraph(
                "Area Analysis",
                section_style,
            )
        )

        area_data = [
            [
                "Measurement",
                "Value",
            ],
            [
                "Total Field Area",
                f"{report.total_area_m2:,.2f} m²",
            ],
            [
                "Visible Vegetated Area",
                f"{report.vegetated_area_m2:,.2f} m²",
            ],
            [
                "Additional Area Needed",
                f"{report.deficit_area_m2:,.2f} m²",
            ],
        ]

        area_table = Table(
            area_data,
            colWidths=[
                90 * mm,
                75 * mm,
            ],
        )

        area_table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        colors.HexColor("#e8f5e9"),
                    ),
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.5,
                        colors.HexColor("#dddddd"),
                    ),
                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold",
                    ),
                    (
                        "ALIGN",
                        (1, 1),
                        (1, -1),
                        "RIGHT",
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        5,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        5,
                    ),
                ]
            )
        )

        story.append(area_table)

    # ========================================================
    # ORIGINAL IMAGE
    # ========================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Field Image",
            section_style,
        )
    )

    original_buffer = io.BytesIO()

    original_pil = PILImage.fromarray(
        original_image
    )

    original_pil.save(
        original_buffer,
        format="PNG",
    )

    original_buffer.seek(0)

    story.append(
        _image_from_buffer(
            original_buffer,
            165 * mm,
            105 * mm,
        )
    )

    story.append(
        Spacer(
            1,
            4 * mm,
        )
    )

    story.append(
        Paragraph(
            f"<b>Image:</b> "
            f"{report.image_path or 'Uploaded field image'}"
            f"<br/><b>Resolution:</b> "
            f"{report.image_width} × "
            f"{report.image_height} pixels"
            f"<br/><b>Grid:</b> "
            f"{report.grid_rows} × "
            f"{report.grid_cols} zones",
            body_style,
        )
    )

    # ========================================================
    # VISUAL ANALYSIS
    # ========================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Vegetation & Zone Analysis",
            section_style,
        )
    )

    # --------------------------------------------------------
    # VEGETATION OVERLAY
    # --------------------------------------------------------

    if overlay_buffer is not None:

        story.append(
            Paragraph(
                "<b>Detected Vegetation</b>",
                body_style,
            )
        )

        story.append(
            _image_from_buffer(
                overlay_buffer,
                165 * mm,
                95 * mm,
            )
        )

        story.append(
            Spacer(
                1,
                5 * mm,
            )
        )

    # --------------------------------------------------------
    # ZONE COVERAGE MAP
    # --------------------------------------------------------

    if heatmap_buffer is not None:

        story.append(
            Paragraph(
                "<b>Zone Coverage Map</b>",
                body_style,
            )
        )

        story.append(
            _image_from_buffer(
                heatmap_buffer,
                150 * mm,
                120 * mm,
            )
        )

        story.append(
            Spacer(
                1,
                12,
            )
        )

    # --------------------------------------------------------
    # VEGETATION CONFIDENCE MAP
    # --------------------------------------------------------

    if confidence_buffer is not None:

        story.append(
            Paragraph(
                "Vegetation Confidence",
                section_style,
            )
        )

        story.append(
            Paragraph(
                "This visualization shows how strongly "
                "different pixels match the RGB vegetation "
                "characteristics used by FieldScanner. "
                "Higher values indicate stronger agreement "
                "with the image-based vegetation model. "
                "This is not a probability and is not a "
                "direct measurement of crop physiological "
                "health.",
                body_style,
            )
        )

        story.append(
            _image_from_buffer(
                confidence_buffer,
                165 * mm,
                105 * mm,
            )
        )

        story.append(
            Spacer(
                1,
                12,
            )
        )

    # ========================================================
    # ZONE SUMMARY
    # ========================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Zone Summary",
            section_style,
        )
    )

    b = report.status_breakdown

    summary_data = [
        [
            "Status",
            "Number of Zones",
            "Share of Grid",
        ],
    ]

    for status in [
        "healthy",
        "moderate",
        "needs_attention",
        "bare",
    ]:

        count = b[status]

        percentage = (
            count / total_cells * 100
            if total_cells
            else 0
        )

        summary_data.append(
            [
                STATUS_LABELS[status],
                str(count),
                f"{percentage:.1f}%",
            ]
        )

    summary_table = Table(
        summary_data,
        colWidths=[
            75 * mm,
            45 * mm,
            45 * mm,
        ],
    )

    summary_style_commands = [
        (
            "BACKGROUND",
            (0, 0),
            (-1, 0),
            colors.HexColor("#e8f5e9"),
        ),
        (
            "FONTNAME",
            (0, 0),
            (-1, 0),
            "Helvetica-Bold",
        ),
        (
            "GRID",
            (0, 0),
            (-1, -1),
            0.5,
            colors.HexColor("#dddddd"),
        ),
        (
            "ALIGN",
            (1, 1),
            (-1, -1),
            "CENTER",
        ),
        (
            "VALIGN",
            (0, 0),
            (-1, -1),
            "MIDDLE",
        ),
        (
            "TOPPADDING",
            (0, 0),
            (-1, -1),
            5,
        ),
        (
            "BOTTOMPADDING",
            (0, 0),
            (-1, -1),
            5,
        ),
    ]

    for row_index, status in enumerate(
        [
            "healthy",
            "moderate",
            "needs_attention",
            "bare",
        ],
        start=1,
    ):

        summary_style_commands.append(
            (
                "TEXTCOLOR",
                (0, row_index),
                (0, row_index),
                _status_color(status),
            )
        )

    summary_table.setStyle(
        TableStyle(
            summary_style_commands
        )
    )

    story.append(
        summary_table
    )

    # ========================================================
    # DETAILED ZONES
    # ========================================================

    story.append(
        Spacer(
            1,
            7 * mm,
        )
    )

    story.append(
        Paragraph(
            "Detailed Zone Analysis",
            section_style,
        )
    )

    zone_data = [
        [
            "Zone",
            "Vegetation",
            "Status",
            "Pixel Area",
            "Real Area",
        ]
    ]

    for cell in report.cells:

        zone_name = (
            f"{cell.row + 1}-{cell.col + 1}"
        )

        vegetation = (
            cell.green_fraction * 100
        )

        real_area = (
            f"{cell.real_area_m2:,.1f} m²"
            if cell.real_area_m2 is not None
            else "—"
        )

        zone_data.append(
            [
                zone_name,
                f"{vegetation:.1f}%",
                STATUS_LABELS.get(
                    cell.status,
                    cell.status,
                ),
                f"{cell.pixel_area:,}",
                real_area,
            ]
        )

    zone_table = Table(
        zone_data,
        repeatRows=1,
        colWidths=[
            22 * mm,
            28 * mm,
            42 * mm,
            32 * mm,
            38 * mm,
        ],
    )

    zone_commands = [
        (
            "BACKGROUND",
            (0, 0),
            (-1, 0),
            colors.HexColor("#e8f5e9"),
        ),
        (
            "FONTNAME",
            (0, 0),
            (-1, 0),
            "Helvetica-Bold",
        ),
        (
            "GRID",
            (0, 0),
            (-1, -1),
            0.35,
            colors.HexColor("#dddddd"),
        ),
        (
            "ALIGN",
            (1, 1),
            (-1, -1),
            "CENTER",
        ),
        (
            "FONTSIZE",
            (0, 0),
            (-1, -1),
            7.5,
        ),
        (
            "TOPPADDING",
            (0, 0),
            (-1, -1),
            3,
        ),
        (
            "BOTTOMPADDING",
            (0, 0),
            (-1, -1),
            3,
        ),
    ]

    zone_table.setStyle(
        TableStyle(
            zone_commands
        )
    )

    story.append(
        zone_table
    )

    # ========================================================
    # INTERPRETATION
    # ========================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Interpretation",
            section_style,
        )
    )

    if coverage >= target_coverage_pct:

        interpretation = (
            f"The analysis detected "
            f"{coverage:.1f}% visible vegetation "
            f"coverage, meeting or exceeding the "
            f"configured target of "
            f"{target_coverage_pct:.1f}%. "
            f"The grid analysis identified "
            f"{b['healthy']} healthy zones out of "
            f"{total_cells} total zones."
        )

    else:

        interpretation = (
            f"The analysis detected "
            f"{coverage:.1f}% visible vegetation "
            f"coverage, which is "
            f"{coverage_gap:.1f} percentage points "
            f"below the configured target of "
            f"{target_coverage_pct:.1f}%. "
            f"{needing} of {total_cells} zones are "
            f"classified as needing attention or bare."
        )

    story.append(
        Paragraph(
            interpretation,
            body_style,
        )
    )

    story.append(
        Paragraph(
            "<b>Analysis recommendation</b>",
            body_style,
        )
    )

    story.append(
        Paragraph(
            report.recommendation,
            body_style,
        )
    )

    # ========================================================
    # METHODOLOGY
    # ========================================================

    story.append(
        Paragraph(
            "Methodology",
            section_style,
        )
    )

    methodology = (
        "FieldScanner analyzes ordinary RGB imagery using "
        "color-based vegetation detection. The primary "
        "vegetation mask combines the Excess Green minus "
        "Excess Red (ExGR) signal with HSV-based confirmation. "
        "The resulting pixel-level vegetation mask is used "
        "to calculate overall visible vegetation coverage "
        "and to divide the image into a configurable grid "
        "of analysis zones."
    )

    story.append(
        Paragraph(
            methodology,
            body_style,
        )
    )

    # ========================================================
    # LIMITATIONS
    # ========================================================

    story.append(
        Paragraph(
            "Important Limitations",
            section_style,
        )
    )

    limitations = (
        "FieldScanner's RGB analysis estimates visible "
        "vegetation coverage and color-based vegetation "
        "characteristics. It is not a direct measurement "
        "of physiological crop health, biomass, nutrient "
        "status, water stress, or yield. Lighting conditions, "
        "shadows, camera characteristics, soil color, image "
        "quality, and other environmental factors can "
        "influence RGB classification. For more advanced "
        "vegetation-health analysis, multispectral imagery "
        "containing Near-Infrared information may be used "
        "with indices such as NDVI."
    )

    story.append(
        Paragraph(
            limitations,
            body_style,
        )
    )

    # ========================================================
    # FINAL STATUS
    # ========================================================

    story.append(
        Spacer(
            1,
            5 * mm,
        )
    )

    status_table = Table(
        [
            [
                Paragraph(
                    "<b>FieldScanner Assessment</b>",
                    body_style,
                ),
                Paragraph(
                    f"<b>{coverage_status}</b>",
                    body_style,
                ),
            ]
        ],
        colWidths=[
            100 * mm,
            60 * mm,
        ],
    )

    status_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    colors.HexColor("#f1f8f2"),
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    1,
                    colors.HexColor("#a5d6a7"),
                ),
                (
                    "ALIGN",
                    (1, 0),
                    (1, 0),
                    "RIGHT",
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ]
        )
    )

    story.append(
        status_table
    )

    # ========================================================
    # BUILD PDF
    # ========================================================

    document.build(
        story,
        onFirstPage=_header_footer,
        onLaterPages=_header_footer,
    )

    pdf_buffer.seek(0)

    return pdf_buffer